name: tibgs_cafe_manager
description: A premium gaming cafe management app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Local Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # UI & Design
  google_fonts: ^6.1.0
  fl_chart: ^0.66.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
